stages:
  - test
  - build
  - deploy
test project:
  stage: test
  image: node:14
  script:
    - npm test
build project:
  stage: build
  image: node:14
  script:
    - npm run build
netlify:
  stage: deploy
  image: node:14
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
