stages:
  - test
  - build
  - deploy
test project:
  stage: test
  image: node:15
  script:
    - npm test 
build project:
  needs: ["test project"]
  stage: build
  image: node:15
  script:
    - npm run build
  artifacts:
    paths:
      - build/
netlify:
  needs: ["build project"]
  stage: deploy
  image: node:15
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
